logger:
  mode: "local"
  debug: true
# http server config
http:
  host: localhost
  port: 5050

runtime:
  maxProcs: 100

# database config
postgresql:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  databaseName: "example_db"
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifetime: "1h"
  parameters: "parseTime=true"
  logSql: true
  autoMigrate: true

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  maxRetries: 2
  poolSize: 10